# Streamlit Secrets Configuration Template
# Copy this file to secrets.toml and fill in your values

# Feedback Configuration
FEEDBACK_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbyyKv4qXfsAjk9Ynk1Q0K6ZLlyR8w7qraxn9uWJcM-iD0S4sN9PwvCnfMTgaJ9HH7Gd8g/exec"

# Development Mode (set to true to show admin features)
DEBUG_MODE = false

# Alternative: Email Configuration (if using email instead of Google Sheets)
# FEEDBACK_EMAIL = "your-email@gmail.com"
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = 587
# SMTP_USERNAME = "your-email@gmail.com"
# SMTP_PASSWORD = "your-app-password"toml