# Streamlit Secrets Configuration Template
# Copy this file to secrets.toml and fill in your values

# Feedback Configuration
FEEDBACK_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbymn2Pyzi7xxqxCiglcRaLZsnrMJV_2KWWNdDxrjODkX-PV3WdrZnJkhOpPA0LGmBYqbQ/exec"

# Development Mode (set to true to show admin features)
DEBUG_MODE = false

# Alternative: Email Configuration (if using email instead of Google Sheets)
# FEEDBACK_EMAIL = "your-email@gmail.com"
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = 587
# SMTP_USERNAME = "your-email@gmail.com"
# SMTP_PASSWORD = "your-app-password"toml